name: shared
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  
  loggy: ^2.0.1+1
  

dev_dependencies:
  analyzer_rules:
    path: ../analyzer_rules
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  
