name: flutter_mobile_app_foundation
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  auto_route: ^7.8.4
  data:
    path: ./packages/data
  domain:
    path: ./packages/domain
  shared:
    path: ./packages/shared
  rxdart: ^0.27.4
  mocktail: ^1.0.3
  mockito: ^5.3.0
  bloc_test: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer_rules:
      path: ./packages/analyzer_rules
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.2.0
  freezed: ^2.1.0+1


flutter:
  uses-material-design: true
