name: analyzer_rules
description: A new Flutter project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  bloc: ^8.1.2
  build_runner: ^2.4.8
  flutter_bloc: ^8.1.3
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.2
