name: domain
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  data:
    path: ../data
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  shared:
    path: ../shared

dev_dependencies:
  analyzer_rules:
    path: ../analyzer_rules
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4
